[features]
seeds = false
skip-lint = false
[programs.localnet]
devnet_token_faucet = "FF2UnZt7Lce3S65tW5cMVKz8iVAPoCS8ETavmUhsWLJB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
